export const BUSINESS_CODES = {
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",

  USER_EXISTS: "USER_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  TENANT_NAME_EXISTS: "TENANT_NAME_EXISTS",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",

  REQUIRED_FIELDS: "REQUIRED_FIELDS",
  BAD_REQUEST: "BAD_REQUEST",

  UNKNOWN: "UNKNOWN_ERROR",
} as const;
